### ISSUE TITLE
Use gpiozero's CPUTemperature

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/temperature-log#10]
http://gpiozero.readthedocs.io/en/stable/api_other.html#cputemperature

**Comment by MarcScott** [comment]
@bennuttall this returns a value between 0 and 1, with no way to actually state the temperature. Can I get the temp in degrees C using gpiozero

**Comment by bennuttall** [comment]
`cpu.temperature`

**Comment by bennuttall** [comment]
That should probably be the first example...

**Comment by MarcScott** [comment]
Cool - couldn't see that in the documentation

**Comment by MarcScott** [comment]
Changed in https://github.com/raspberrypilearning/temperature-log/tree/gpiozero-update and awaiting copy edit
