### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/temperature-log#2]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by bennuttall** [comment]
Titles need shortening

**Comment by TeCoEd** [comment]
Added / edited the the learn, hardware and make files in line with the template training, thanks.
