### ISSUE TITLE
SoC 

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/temperature-log#5]
The tutorial is written for earlier versions of the board using the Broadcom BCM2835, which is also shown in the SoC image (original model B). I know the Pi 2 uses the Broadcom BCM2836: can I assume that this tutorial still works in the same way, regardless of which SoC is being used? 
Also, are we happy with the chip image, or do we have an image of the BCM2836 to use?

**Comment by TeCoEd** [comment]
Hi, I tested the code and steps on the Pi2 and all worked correctly.

**Comment by LizUpton** [comment]
Hi @LornaLynch - anything written for Pi 1 will work on Pi 2: the SoC is completely backwards compatible.

**Comment by LornaLynch** [comment]
Thanks guys: I suspected it would be but wasn't 100% certain.
