### ISSUE TITLE
Missing text? 

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/temperature-log#6]
"Creating a Shell Script", step 2: it seems that there might be a word missing here. Should the sentence run "After that, you can move **the code** with the cursor and write into the file", or something similar?

**Comment by TeCoEd** [comment]
How about, 
"Use the cursor to move and select where you want to write the code."

**Comment by LornaLynch** [comment]
Thanks! I sometimes find these things hard to guess, as I'm not au fait with coding.
